### PR TITLE
feat: responsive design

### PR DESCRIPTION
**Pull request by louisunlimited**
## Done:
- [x] Added responsive to Dashboard

## TODO:
- [ ] ~Design for Event detail page~
- [ ] ~Implement design for event detail page~

### CODE REVIEW

**Comment by RaymondWHZ** [comment]
Can we make the style of this button more consistent with the style of a primary button?
Screenshot 2023-05-21 at 8 24 57 AM
A primary button:
Screenshot 2023-05-21 at 8 25 03 AM
You might use the `primary-button` style (see globals.css).

**Comment by RaymondWHZ** [comment]
Can we make this dialog justify to the top so that the position of the tab buttons will be the same on the screen? This might benefit user operation.

Screenshot 2023-05-21 at 8 29 01 AM
Screenshot 2023-05-21 at 8 29 04 AM

**Comment by RaymondWHZ** [comment]
Also, we can merge this pr upon finishing the responsive design for the navbar and dashboard only. Leave responsive design for detail page to a later update.

**Comment by louisunlimited** [comment]
> Can we make this dialog justify to the top so that the position of the tab buttons will be the same on the screen? This might benefit user operation.
> 
> Screenshot 2023-05-21 at 8 29 01 AM Screenshot 2023-05-21 at 8 29 04 AM

What do you mean by "justify to top"

**Comment by RaymondWHZ** [comment]
> What do you mean by "justify to top"

This means keeping a constant distance (for a certain screen) between the top of the screen and the top of the dialog instead of putting the dialog at the center of the screen. This will create a similar behavior to the desktop view, where the position of tab buttons (Start New and Join Existing) on the screen is the same for both tabs.

**Comment by louisunlimited** [comment]
> > What do you mean by "justify to top"
> 
> This means keeping a constant distance (for a certain screen) between the top of the screen and the top of the dialog instead of putting the dialog at the center of the screen. This will create a similar behavior to the desktop view, where the position of tab buttons (Start New and Join Existing) on the screen is the same for both tabs.
> 
> Screenshot 2023-05-24 at 11 02 10 AM Screenshot 2023-05-24 at 11 02 14 AM

I already did this, check my code for ref

**Comment by RaymondWHZ** [comment]
I see no problem. I'll merge this if you have finished with it.

**Comment by louisunlimited** [comment]
> I see no problem. I'll merge this if you have finished with it.


Sure, the button text seems a bit too long tho, and we'll still need to do responsive for Galaxy Fold

**Comment by RaymondWHZ** [comment]
> Sure, the button text seems a bit too long tho, and we'll still need to do responsive for Galaxy Fold

I agree it is too long. Fixed. We can leave responsive for Galaxy Fold to later since it is an extreme case.

**Comment by louisunlimited** [comment]
> > Sure, the button text seems a bit too long tho, and we'll still need to do responsive for Galaxy Fold
> 
> I agree it is too long. Fixed. We can leave responsive for Galaxy Fold to later since it is an extreme case.

Great, this pr can be merged then!

**Review by RaymondWHZ — APPROVED** [review]
Really nice work!

**Pull request merged**
