### PR TITLE
feat: delete participants if owner

### LINKED ISSUE #53: feat: allow owner to remove participants
Event owners should be able to remove any other participants from their events.

### PR DESCRIPTION
**Pull request by louisunlimited**
- Fixes #53 

Added edit functionality in `edit` button
Screenshot 2023-05-25 at 15 53 48

### CODE REVIEW

**Comment by louisunlimited** [comment]
It'll be great if someone else want to test this code for me XD

**Comment by RaymondWHZ** [comment]
I have quickly fixed several things here. We can merge this PR if you think it is ready!

**Comment by louisunlimited** [comment]
> I have quickly fixed several things here. We can merge this PR if you think it is ready!

Everything looks nice! Let's merge this then

**Review by RaymondWHZ — APPROVED** [review]
Great work as always!

**Pull request merged**
